import type { Metadata } from "next";
import { IBM_Plex_Mono, VT323} from "next/font/google";
import "./globals.css";
import FlickerEffect from "@/components/flicker";

const vT = VT323({
  variable: "--font-VT323",
  weight: '400',
  subsets: ["latin"],
});

const ibmPlex = IBM_Plex_Mono({
  variable: "--font-IBM_Plex_Mono",
  weight: '400',
  subsets:["latin"]

})

export const metadata: Metadata = {
  title: "Profile Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vT.variable} ${ibmPlex.variable} antialiased`}>
          <FlickerEffect />
        {children}
      </body>
    </html>
  );
}


